### PR TITLE
e2e test with apicast deployed exposing an ingress

### PR DESCRIPTION
**Pull request by eguzki**

### CODE REVIEW

**Comment by eguzki** [comment]
It is expected to fail when running on OCP. That is this test is about. 

When rebased on top of the fix https://github.com/3scale/apicast-operator/pull/56 all tests should pass

**Comment by thomasmaas** [comment]
Just curious, could this potentially be a very slow test?

**Comment by miguelsorianod** [comment]
> Just curious, could this potentially be a very slow test?

What this test is specifically checking is not very slow. What is slow is what all e2e tests share, which is the environment set up time: This is, deploying the K8s/OpenShift cluster, deploying the operator, ...

**Comment by eguzki** [comment]
Now, all the tests are expected to pass

**Pull request merged**
