### PR TITLE
THREESCALE-10882 bump the version

### PR DESCRIPTION
**Pull request by austincunningham**
# What
bump the vesion

# Verification
CI passes

### CODE REVIEW

**Review by eguzki — COMMENTED** [review]
Changelog? https://github.com/3scale/apicast-operator/pull/186/files

**Comment by austincunningham** [comment]
> Changelog? https://github.com/3scale/apicast-operator/pull/186/files

@eguzki do we need to this for a MAS release ? Guess there is no harm either way

**Comment by eguzki** [comment]
Then, you need to bring the changes to `master`.

**Pull request merged**
