### PR TITLE
THREESCALE-9985: go1.19

### PR DESCRIPTION
**Pull request by eguzki**
Fixes https://issues.redhat.com/browse/THREESCALE-9985

### CODE REVIEW

**Comment by Patryk-Stefanski** [comment]
should this pr include `go.sum` as well?

**Comment by eguzki** [comment]
> should this pr include `go.sum` as well?

no changes in `go.sum` :shrug:

**Comment by Patryk-Stefanski** [comment]
Are there any verification steps for this or is the code running enough?

**Comment by eguzki** [comment]
code running is enough, which happens in the e2e tests,which pass.

**Comment by Patryk-Stefanski** [comment]
ah nice, in that case
/lgtm

**Review by austincunningham — APPROVED** [review]

**Pull request merged**
